<a href="https://colab.research.google.com/github/piyushjain220/TSAI/blob/main/NLP/Resources/Difficult_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import random

In [ ]:
import torch
import torchvision # provide access to datasets, models, transforms, utils, etc
import torchvision.transforms as transforms

In [ ]:
# let's extend the Dataset class of Pytorch to build our own nums dataset
from torch.utils.data import Dataset
import random
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

class NumbersDataset(Dataset):
  def __init__(self):
    pass

  def __getitem__(self, index):
    num1 = random.choice(numbers)
    num2 = random.choice(numbers)
    add_res = torch.tensor(num1 + num2, dtype=torch.float32)
    nums = torch.tensor([num1, num2], dtype=torch.float32)
    return nums, add_res
  
  def __len__(self):
    return 1000

In [ ]:
m_dataset = NumbersDataset()

In [ ]:
next(iter(m_dataset))

(tensor([6., 4.]), tensor(10.))

In [ ]:
train_loader = torch.utils.data.DataLoader(m_dataset
    ,batch_size=10
    ,shuffle=False
)

next(iter(train_loader))

[tensor([[1., 6.],
         [7., 3.],
         [9., 2.],
         [8., 8.],
         [7., 5.],
         [2., 7.],
         [6., 2.],
         [9., 2.],
         [6., 2.],
         [2., 2.]]),
 tensor([ 7., 10., 11., 16., 12.,  9.,  8., 11.,  8.,  4.])]

In [ ]:
import torch.nn.functional as F
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(in_features=2, out_features=10, bias=False)
        self.fc2 = nn.Linear(in_features=10, out_features=10, bias=False)
        self.out = nn.Linear(in_features=10, out_features=1, bias=False)

    def forward(self, t):
        t = self.fc1(t)
        t = F.relu(t)
        t = self.fc2(t)
        t = F.relu(t)
        t = self.out(t)

        return t

In [ ]:
network = Network()
pred = network(next(iter(m_dataset))[0])
pred

tensor([0.3219], grad_fn=<SqueezeBackward3>)

In [ ]:
import torch.optim as optim
import math

network = Network()

train_loader = torch.utils.data.DataLoader(m_dataset, batch_size=10000000)
optimizer = optim.Adam(network.parameters(), lr=0.1)

total_loss = 0
total_correct = 0

for epoch in range(20):

    total_loss = 0
    total_correct = 0
    if epoch == 10:
      optimizer = optim.Adam(network.parameters(), lr=0.001)
    for batch in train_loader: # Get Batch
        nums, add_res = batch 

        preds = network(nums) # Pass Batch
        add_res = add_res.type(torch.FloatTensor)
        loss = F.mse_loss(preds, add_res) # Calculate Loss

        optimizer.zero_grad()
        loss.backward() # Calculate Gradients
        optimizer.step() # Update Weights

        total_loss += loss.item()

    print(
        "epoch:", epoch, 
        "loss:", total_loss
    )


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: UserWarning: Using a target size (torch.Size([1000])) that is different to the input size (torch.Size([1000, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.


epoch: 0 loss: 111.69872283935547
epoch: 1 loss: 89.619873046875
epoch: 2 loss: 48.00177764892578
epoch: 3 loss: 24.836925506591797
epoch: 4 loss: 61.17211151123047
epoch: 5 loss: 38.62464904785156
epoch: 6 loss: 25.989276885986328
epoch: 7 loss: 30.433700561523438
epoch: 8 loss: 39.1937370300293
epoch: 9 loss: 41.257164001464844
epoch: 10 loss: 41.45707702636719
epoch: 11 loss: 38.92074966430664
epoch: 12 loss: 38.77179718017578
epoch: 13 loss: 38.51563262939453
epoch: 14 loss: 38.24116516113281
epoch: 15 loss: 39.28142547607422
epoch: 16 loss: 37.93470001220703
epoch: 17 loss: 37.18488693237305
epoch: 18 loss: 35.618194580078125
epoch: 19 loss: 36.34186553955078


In [ ]:
X = torch.tensor([1., 0.])
pred = network(X)
pred, X

(tensor([0.6753], grad_fn=<SqueezeBackward3>), tensor([1., 0.]))